In [15]:
# if you're missing any of the below libraries, install here. 
import sys
!{sys.executable} -m pip install jupyter_dash

Collecting jupyter_dash
  Downloading jupyter_dash-0.3.1-py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 1.5 MB/s eta 0:00:01
Requirement already satisfied: ipykernel in /opt/anaconda3/lib/python3.7/site-packages (from jupyter_dash) (5.1.4)
Requirement already satisfied: ipython in /opt/anaconda3/lib/python3.7/site-packages (from jupyter_dash) (7.12.0)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.7/site-packages (from jupyter_dash) (2.22.0)
Collecting ansi2html
  Downloading ansi2html-1.5.2.tar.gz (27 kB)
Requirement already satisfied: dash in /opt/anaconda3/lib/python3.7/site-packages (from jupyter_dash) (1.16.2)
Requirement already satisfied: retrying in /opt/anaconda3/lib/python3.7/site-packages (from jupyter_dash) (1.3.3)
Requirement already satisfied: flask in /opt/anaconda3/lib/python3.7/site-packages (from jupyter_dash) (1.1.1)
Requirement already satisfied: appnope; platform_system == "Darwin" in /opt/anaconda3/lib/python3.7/site-packages (from ipykernel->jupyter_dash) (0.1.0)
Requirement already satisfied: traitlets>=4.1.0 in /opt/anaconda3/lib/python3.7/site-packages (from ipykernel->jupyter_dash) (4.3.3)
Requirement already satisfied: jupyter-client in /opt/anaconda3/lib/python3.7/site-packages (from ipykernel->jupyter_dash) (5.3.4)
Requirement already satisfied: tornado>=4.2 in /opt/anaconda3/lib/python3.7/site-packages (from ipykernel->jupyter_dash) (6.0.3)
Requirement already satisfied: jedi>=0.10 in /opt/anaconda3/lib/python3.7/site-packages (from ipython->jupyter_dash) (0.14.1)
Requirement already satisfied: pygments in /opt/anaconda3/lib/python3.7/site-packages (from ipython->jupyter_dash) (2.5.2)
Requirement already satisfied: pickleshare in /opt/anaconda3/lib/python3.7/site-packages (from ipython->jupyter_dash) (0.7.5)
Requirement already satisfied: backcall in /opt/anaconda3/lib/python3.7/site-packages (from ipython->jupyter_dash) (0.1.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/anaconda3/lib/python3.7/site-packages (from ipython->jupyter_dash) (3.0.3)
Requirement already satisfied: decorator in /opt/anaconda3/lib/python3.7/site-packages (from ipython->jupyter_dash) (4.4.1)
Requirement already satisfied: setuptools>=18.5 in /opt/anaconda3/lib/python3.7/site-packages (from ipython->jupyter_dash) (46.0.0.post20200309)
Requirement already satisfied: pexpect; sys_platform != "win32" in /opt/anaconda3/lib/python3.7/site-packages (from ipython->jupyter_dash) (4.8.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.7/site-packages (from requests->jupyter_dash) (2019.11.28)
Requirement already satisfied: idna<2.9,>=2.5 in /opt/anaconda3/lib/python3.7/site-packages (from requests->jupyter_dash) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/anaconda3/lib/python3.7/site-packages (from requests->jupyter_dash) (1.25.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/anaconda3/lib/python3.7/site-packages (from requests->jupyter_dash) (3.0.4)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.7/site-packages (from ansi2html->jupyter_dash) (1.14.0)
Requirement already satisfied: future in /opt/anaconda3/lib/python3.7/site-packages (from dash->jupyter_dash) (0.18.2)
Requirement already satisfied: dash-html-components==1.1.1 in /opt/anaconda3/lib/python3.7/site-packages (from dash->jupyter_dash) (1.1.1)
Requirement already satisfied: flask-compress in /opt/anaconda3/lib/python3.7/site-packages (from dash->jupyter_dash) (1.5.0)
Requirement already satisfied: dash-core-components==1.12.1 in /opt/anaconda3/lib/python3.7/site-packages (from dash->jupyter_dash) (1.12.1)
Requirement already satisfied: dash-table==4.10.1 in /opt/anaconda3/lib/python3.7/site-packages (from dash->jupyter_dash) (4.10.1)
Requirement already satisfied: plotly in /opt/anaconda3/lib/python3.7/site-packages (from dash->jupyter_dash) (4.10.0)
Requirement already satisfied: dash-renderer==1.8.2 in /opt/anaconda3/lib/python3.7/site-packages (from dash->jupyter_dash) (1.8.2)
Requirement already satisfied: Werkzeug>=0.15 in /opt/anaconda3/lib/python3.7/site-packages (from flask->jupyter_dash) (1.0.0)
Requirement already satisfied: click>=5.1 in /opt/anaconda3/lib/python3.7/site-packages (from flask->jupyter_dash) (7.0)
Requirement already satisfied: itsdangerous>=0.24 in /opt/anaconda3/lib/python3.7/site-packages (from flask->jupyter_dash) (1.1.0)
Requirement already satisfied: Jinja2>=2.10.1 in /opt/anaconda3/lib/python3.7/site-packages (from flask->jupyter_dash) (2.11.1)
Requirement already satisfied: ipython-genutils in /opt/anaconda3/lib/python3.7/site-packages (from traitlets>=4.1.0->ipykernel->jupyter_dash) (0.2.0)
Requirement already satisfied: pyzmq>=13 in /opt/anaconda3/lib/python3.7/site-packages (from jupyter-client->ipykernel->jupyter_dash) (18.1.1)
Requirement already satisfied: jupyter-core>=4.6.0 in /opt/anaconda3/lib/python3.7/site-packages (from jupyter-client->ipykernel->jupyter_dash) (4.6.1)
Requirement already satisfied: python-dateutil>=2.1 in /opt/anaconda3/lib/python3.7/site-packages (from jupyter-client->ipykernel->jupyter_dash) (2.8.1)
Requirement already satisfied: parso>=0.5.0 in /opt/anaconda3/lib/python3.7/site-packages (from jedi>=0.10->ipython->jupyter_dash) (0.5.2)
Requirement already satisfied: wcwidth in /opt/anaconda3/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->jupyter_dash) (0.1.8)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/lib/python3.7/site-packages (from pexpect; sys_platform != "win32"->ipython->jupyter_dash) (0.6.0)
Requirement already satisfied: brotli in /opt/anaconda3/lib/python3.7/site-packages (from flask-compress->dash->jupyter_dash) (1.0.9)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/anaconda3/lib/python3.7/site-packages (from Jinja2>=2.10.1->flask->jupyter_dash) (1.1.1)
Building wheels for collected packages: ansi2html
  Building wheel for ansi2html (setup.py) ... done
  Created wheel for ansi2html: filename=ansi2html-1.5.2-py3-none-any.whl size=13860 sha256=2f31976cb514aff421de0c63d40dd99b319320d8466de1aa3b94a35e90006865
  Stored in directory: /Users/jonathancheung/Library/Caches/pip/wheels/62/fa/1e/1ad9fb5c2225613adfcf012dd25f313f3a065f2131cdff0a99
Successfully built ansi2html
Installing collected packages: ansi2html, jupyter-dash
Successfully installed ansi2html-1.5.2 jupyter-dash-0.3.1

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime as dt
import pgeocode
import quandl

In [7]:
# import reference df for regions
# region_df = pd.read_csv(r'C:\Users\jacheung\Dropbox\Datasets\Zillow\ZILLOW-REGIONS.csv')
# indicators_df = pd.read_csv(r'C:\Users\jacheung\Dropbox\Datasets\Zillow\ZILLOW_INDICATORS.csv')

region_df = pd.read_csv(r'/Users/jonathancheung/Dropbox/Datasets/Zillow/ZILLOW-REGIONS.csv')
indicators_df = pd.read_csv(r'/Users/jonathancheung/Dropbox/Datasets/Zillow/ZILLOW_INDICATORS.csv')


la_region_id = region_df[region_df['region'].str.contains('Los Angeles', regex=False)]
la_region_id.reset_index(drop=True,inplace=True)

In [8]:
# build a look up table for los angeles
# extract out zip codes
zipcode = [k.split(';')[0] for k in la_region_id['region'] if k.split(';')[0].isdigit()]
idx = [idx for idx,k in enumerate(la_region_id['region']) if k.split(';')[0].isdigit()]
la_lookup = la_region_id.loc[idx]
la_lookup['zipcode'] = zipcode

# transform zip codes to lat long
nomi = pgeocode.Nominatim('us')
def get_lat_long(zipcode):
    vals = nomi.query_postal_code(zipcode)
    return vals['latitude'], vals['longitude']

lat_long_raw = [get_lat_long(k) for k in la_lookup['zipcode']]
lat_long_insert =np.array([np.array(xi) for xi in lat_long_raw])

la_lookup['latitude'] = lat_long_insert[:,0]
la_lookup['longitude'] = lat_long_insert[:,1]

In [52]:
# build median home values across all zip codes using quandl API
quandl.ApiConfig.api_key = 'wX4VKujcwjcKqguwo1hR'
df = pd.DataFrame()
for region_id, zipcode in zip(la_lookup['region_id'],la_lookup['zipcode']):
    data = quandl.get_table('ZILLOW/DATA', indicator_id='ZSFH', region_id=str(region_id))
    data['date'] = data['date'].astype('datetime64[M]')
    data['value'] = data['value']/10**6
    group_data = data.groupby(by=['date']).aggregate('median').rename(columns = {'value':zipcode})
    df = pd.concat([df, group_data], axis=1)
    
df.reset_index(inplace=True)

pct_df = df.loc[:,(df.columns != 'date')].pct_change(axis=0,periods=12)
pct_df = pd.concat([pct_df,df['date']],axis=1)

In [63]:
# bokeh plotting 
from bokeh.plotting import figure
from bokeh.io import output_file,show
from bokeh.models import HoverTool, CategoricalColorMapper, ColumnDataSource
from bokeh.models.widgets import Tabs, Panel

source = ColumnDataSource(df)

p = figure(title = 'SFH house price', x_axis_type = 'datetime', 
           x_axis_label = 'Date', y_axis_label = 'House price in millions (USD)')

p.circle('date', '90047', source=source, size =3, color = 'red', legend_label='Westmont')
p.circle('date', '90010', source=source, size =3,color = 'blue')
p.circle('date', '90005', source=source, size =3,color = 'blue')
p.circle('date', '90007', source=source, size =3,color = 'green', legend_label='North USC')
p.circle('date', '90006', source=source, size =3,color = 'blue', legend_label='Koreatown')
p.legend.location = "top_left"

source = ColumnDataSource(pct_df)
p1 = figure(title = 'SFH house price', x_axis_type = 'datetime', 
           x_axis_label = 'Date', y_axis_label = 'Yearly percent change in house price')
p1.circle('date', '90047', source=source, size =3, color = 'red', legend_label = 'Westmont')
p1.circle('date', '90010', source=source, size =3,color = 'blue')
p1.circle('date', '90005', source=source, size =3,color = 'blue')
p1.circle('date', '90007', source=source, size =3,color = 'green', legend_label='North USC')
p1.circle('date', '90006', source=source, size =3,color = 'blue', legend_label = 'Koreatown')
p1.legend.location = "top_left"

tab1 = Panel(child=p, title='Median home values')
tab2 = Panel(child=p1, title='Yearly percent change')

# Create a Tabs layout: layout
layout = Tabs(tabs=[tab1, tab2])
show(layout)

In [64]:
df

,date,93591,93563,93553,93552,93551,93550,93544,93543,93536,...,90011,90010,90008,90007,90006,90005,90004,90003,90002,90001
0,1996-01-01,NaN,NaN,0.092492,NaN,0.140699,NaN,0.136140,NaN,0.118756,...,NaN,NaN,0.225003,0.162066,0.158540,0.158799,0.122969,NaN,NaN,NaN
1,1996-02-01,NaN,NaN,0.091676,NaN,0.140913,NaN,0.134742,NaN,0.118681,...,NaN,NaN,0.225254,0.161673,0.157562,0.158163,0.123410,NaN,NaN,NaN
2,1996-03-01,NaN,NaN,0.090939,NaN,0.141034,NaN,0.133518,NaN,0.118666,...,NaN,NaN,0.225578,0.161970,0.157062,0.158820,0.123708,NaN,NaN,NaN
3,1996-04-01,NaN,NaN,0.089558,NaN,0.141409,NaN,0.131044,NaN,0.118543,...,NaN,NaN,0.226041,0.162309,0.155928,0.159642,0.124277,NaN,NaN,NaN
4,1996-05-01,NaN,NaN,0.089060,NaN,0.141681,NaN,0.129496,NaN,0.118421,...,NaN,NaN,0.226932,0.163348,0.155388,0.161199,0.124959,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,2020-04-01,0.242654,0.257225,0.297812,0.334519,0.419300,0.303622,0.304501,0.302729,0.381522,...,0.473896,1.739697,0.962129,0.812015,0.898794,1.713581,1.609627,0.447436,0.419855,0.429415
292,2020-05-01,0.242848,0.244280,0.288614,0.334422,0.418672,0.303030,0.288219,0.300749,0.381353,...,0.473437,1.633478,0.944837,0.778383,0.884229,1.693056,1.619333,0.443471,0.420023,0.427582
293,2020-06-01,0.242303,0.250259,0.289446,0.336994,0.420667,0.304589,0.286104,0.304017,0.384036,...,0.478062,1.706485,0.948435,0.790253,0.869641,1.730113,1.620176,0.449426,0.424226,0.430023
294,2020-07-01,0.243441,0.250871,0.293086,0.339071,0.423186,0.306564,0.286866,0.307263,0.386719,...,0.485080,1.727616,0.955108,0.794776,0.874650,1.723200,1.621155,0.452862,0.427053,0.434048
295,2020-08-01,0.245256,0.251855,0.296932,0.342382,0.427316,0.309540,0.286960,0.311530,0.390897,...,0.493652,1.766255,0.966887,0.803713,0.884541,1.719298,1.627275,0.457516,0.431692,0.439685

In [17]:
import dash
from jupyter_dash import JupyterDash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output

scatter_df = df.set_index('date').transpose()
scatter_df = pd.concat([scatter_df, la_lookup.set_index('zipcode')], axis=1, sort=False)
scatter_df.drop(columns = ['region_id', 'region_type','region'], inplace=True)

time_idx = [idx for idx, k in enumerate(scatter_df.columns) if type(k) == type(pd.to_datetime(dt.now()))]
sel_dates = scatter_df.columns[time_idx]
keys = [val for idx, val in enumerate(sel_dates) if ((idx+1)/6).is_integer()]
values = [str(val.month) + '/' + str(val.year) for val in keys]
res = {keys[i]: values[i] for i in range(len(keys))} 


slim_df = scatter_df[res.keys()]
slim_df = pd.concat([slim_df, la_lookup.set_index('zipcode')], axis=1, sort=False)
slim_df.drop(columns = ['region_id', 'region_type','region'], inplace=True)
slim_df = slim_df.rename(columns = res)
res = {values[i]: values[i] for i in range(len(values))} 

app = JupyterDash(__name__)
# app = dash.Dash(__name__)

app.layout = html.Div([
    dcc.Slider(
        id='year-slider',
        min=values[0],
        max=values[-1],
        value=values[0],
        step=None,
        marks=res),
    dcc.Graph(id='graph-with-slider')

])

@app.callback(
    Output('graph-with-slider', 'figure'),
    [Input('year-slider', 'value')])
def update_figure(selected_year):
    year = str(selected_year)
#     year = pd.to_datetime(selected_year)
#     selected_df = scatter_df[[year,'latitude','longitude']].dropna()
#     selected_df[year] = selected_df[year]/10
    selected_df = slim_df[[year,'latitude','longitude']].dropna()
    selected_df[year] = selected_df[year]/10
    fig = px.scatter_mapbox(selected_df, lat="latitude", 
                            lon="longitude", 
                            hover_data=[selected_df.index],
                            size = year)

    fig.update_layout(mapbox_style='open-street-map',transition_duration=500)
    
    return fig
# 
# app.run_server(debug=True)
app.run_server(mode='inline')

KeyboardInterrupt:

In [235]:
slim_df['6/1996']

zipcode
93591         NaN
93563         NaN
93553    0.089212
93552         NaN
93551    0.142160
           ...
90005    0.162517
90004    0.125540
90003         NaN
90002         NaN
90001         NaN
Name: 6/1996, Length: 361, dtype: float64

In [81]:

import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output


time_idx = [idx for idx, k in enumerate(scatter_df.columns) if type(k) == type(pd.to_datetime(dt.now()))]
sel_dates = scatter_df.columns[time_idx]

external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)


app.layout = html.Div([
    dcc.Graph(id='graph-with-slider'),
    dcc.Slider(
        id='year-slider',
        min=sel_dates.min(),
        max=sel_dates.max(),
        value=sel_dates.min(),
        marks={str(year): str(year) for year in sel_dates.unique()},
        step=None
    )
])


@app.callback(
    Output('graph-with-slider', 'figure'),
    [Input('year-slider', 'value')])

def update_figure(selected_year):
    
    fig = px.scatter_mapbox(scatter_df, lat="latitude", lon="longitude", hover_data=[scatter_df.index], size =selected_year)
    fig.update_layout(mapbox_style='open-street-map',transition_duration=500)
    
    return fig


app.run_server(debug=True)

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on

SystemExit: 1

In [82]:
{str(year): str(year) for year in sel_dates.unique()}

{'1996-01-01 00:00:00': '1996-01-01 00:00:00',
 '1996-02-01 00:00:00': '1996-02-01 00:00:00',
 '1996-03-01 00:00:00': '1996-03-01 00:00:00',
 '1996-04-01 00:00:00': '1996-04-01 00:00:00',
 '1996-05-01 00:00:00': '1996-05-01 00:00:00',
 '1996-06-01 00:00:00': '1996-06-01 00:00:00',
 '1996-07-01 00:00:00': '1996-07-01 00:00:00',
 '1996-08-01 00:00:00': '1996-08-01 00:00:00',
 '1996-09-01 00:00:00': '1996-09-01 00:00:00',
 '1996-10-01 00:00:00': '1996-10-01 00:00:00',
 '1996-11-01 00:00:00': '1996-11-01 00:00:00',
 '1996-12-01 00:00:00': '1996-12-01 00:00:00',
 '1997-01-01 00:00:00': '1997-01-01 00:00:00',
 '1997-02-01 00:00:00': '1997-02-01 00:00:00',
 '1997-03-01 00:00:00': '1997-03-01 00:00:00',
 '1997-04-01 00:00:00': '1997-04-01 00:00:00',
 '1997-05-01 00:00:00': '1997-05-01 00:00:00',
 '1997-06-01 00:00:00': '1997-06-01 00:00:00',
 '1997-07-01 00:00:00': '1997-07-01 00:00:00',
 '1997-08-01 00:00:00': '1997-08-01 00:00:00',
 '1997-09-01 00:00:00': '1997-09-01 00:00:00',
 '1997-10-01 00:00:00': '1997-10-01 00:00:00',
 '1997-11-01 00:00:00': '1997-11-01 00:00:00',
 '1997-12-01 00:00:00': '1997-12-01 00:00:00',
 '1998-01-01 00:00:00': '1998-01-01 00:00:00',
 '1998-02-01 00:00:00': '1998-02-01 00:00:00',
 '1998-03-01 00:00:00': '1998-03-01 00:00:00',
 '1998-04-01 00:00:00': '1998-04-01 00:00:00',
 '1998-05-01 00:00:00': '1998-05-01 00:00:00',
 '1998-06-01 00:00:00': '1998-06-01 00:00:00',
 '1998-07-01 00:00:00': '1998-07-01 00:00:00',
 '1998-08-01 00:00:00': '1998-08-01 00:00:00',
 '1998-09-01 00:00:00': '1998-09-01 00:00:00',
 '1998-10-01 00:00:00': '1998-10-01 00:00:00',
 '1998-11-01 00:00:00': '1998-11-01 00:00:00',
 '1998-12-01 00:00:00': '1998-12-01 00:00:00',
 '1999-01-01 00:00:00': '1999-01-01 00:00:00',
 '1999-02-01 00:00:00': '1999-02-01 00:00:00',
 '1999-03-01 00:00:00': '1999-03-01 00:00:00',
 '1999-04-01 00:00:00': '1999-04-01 00:00:00',
 '1999-05-01 00:00:00': '1999-05-01 00:00:00',
 '1999-06-01 00:00:00': '1999-06-01 00:00:00',
 '1999-07-01 00:00:00': '1999-07-01 00:00:00',
 '1999-08-01 00:00:00': '1999-08-01 00:00:00',
 '1999-09-01 00:00:00': '1999-09-01 00:00:00',
 '1999-10-01 00:00:00': '1999-10-01 00:00:00',
 '1999-11-01 00:00:00': '1999-11-01 00:00:00',
 '1999-12-01 00:00:00': '1999-12-01 00:00:00',
 '2000-01-01 00:00:00': '2000-01-01 00:00:00',
 '2000-02-01 00:00:00': '2000-02-01 00:00:00',
 '2000-03-01 00:00:00': '2000-03-01 00:00:00',
 '2000-04-01 00:00:00': '2000-04-01 00:00:00',
 '2000-05-01 00:00:00': '2000-05-01 00:00:00',
 '2000-06-01 00:00:00': '2000-06-01 00:00:00',
 '2000-07-01 00:00:00': '2000-07-01 00:00:00',
 '2000-08-01 00:00:00': '2000-08-01 00:00:00',
 '2000-09-01 00:00:00': '2000-09-01 00:00:00',
 '2000-10-01 00:00:00': '2000-10-01 00:00:00',
 '2000-11-01 00:00:00': '2000-11-01 00:00:00',
 '2000-12-01 00:00:00': '2000-12-01 00:00:00',
 '2001-01-01 00:00:00': '2001-01-01 00:00:00',
 '2001-02-01 00:00:00': '2001-02-01 00:00:00',
 '2001-03-01 00:00:00': '2001-03-01 00:00:00',
 '2001-04-01 00:00:00': '2001-04-01 00:00:00',
 '2001-05-01 00:00:00': '2001-05-01 00:00:00',
 '2001-06-01 00:00:00': '2001-06-01 00:00:00',
 '2001-07-01 00:00:00': '2001-07-01 00:00:00',
 '2001-08-01 00:00:00': '2001-08-01 00:00:00',
 '2001-09-01 00:00:00': '2001-09-01 00:00:00',
 '2001-10-01 00:00:00': '2001-10-01 00:00:00',
 '2001-11-01 00:00:00': '2001-11-01 00:00:00',
 '2001-12-01 00:00:00': '2001-12-01 00:00:00',
 '2002-01-01 00:00:00': '2002-01-01 00:00:00',
 '2002-02-01 00:00:00': '2002-02-01 00:00:00',
 '2002-03-01 00:00:00': '2002-03-01 00:00:00',
 '2002-04-01 00:00:00': '2002-04-01 00:00:00',
 '2002-05-01 00:00:00': '2002-05-01 00:00:00',
 '2002-06-01 00:00:00': '2002-06-01 00:00:00',
 '2002-07-01 00:00:00': '2002-07-01 00:00:00',
 '2002-08-01 00:00:00': '2002-08-01 00:00:00',
 '2002-09-01 00:00:00': '2002-09-01 00:00:00',
 '2002-10-01 00:00:00': '2002-10-01 00:00:00',
 '2002-11-01 00:00:00': '2002-11-01 00:00:00',
 '2002-12-01 00:00:00': '2002-12-01 00:00:00',
 '2003-01-01 00:00:00': '2003-01-01 00:00:00',
 '2003-02-01 00:00:00': '2003-02-01 00:00:00',
 '2003-03-01 00:00:00': '2003-03-01 00:00:00',
 '2003-04-01 00:00:00': '2003-04-01 00:00:00',
 '2003-05-01 00:00:00': '2003-05-01 00:00:00',
 '2003-06-01 00:00:00': '2003-06-01 00:00:00',
 '2003-07-01 00:00:00': '2003-07-01 00:00:00',
 '2003-08-01 00:00:00': '2003-08-01 00:00:00',
 '2003-09-01 00:00:00': '2003-09-01 00:00:00',
 '2003-10-01 00:00:00': '2003-10-01 00:00:00',
 '2003-11-01 00:00:00': '2003-11-01 00:00:00',
 '2003-12-01 00:00:00': '2003-12-01 00:00:00',
 '2004-01-01 00:00:00': '2004-01-01 00:00:00',
 '2004-02-01 00:00:00': '2004-02-01 00:00:00',
 '2004-03-01 00:00:00': '2004-03-01 00:00:00',
 '2004-04-01 00:00:00': '2004-04-01 00:00:00',
 '2004-05-01 00:00:00': '2004-05-01 00:00:00',
 '2004-06-01 00:00:00': '2004-06-01 00:00:00',
 '2004-07-01 00:00:00': '2004-07-01 00:00:00',
 '2004-08-01 00:00:00': '2004-08-01 00:00:00',
 '2004-09-01 00:00:00': '2004-09-01 00:00:00',
 '2004-10-01 00:00:00': '2004-10-01 00:00:00',
 '2004-11-01 00:00:00': '2004-11-01 00:00:00',
 '2004-12-01 00:00:00': '2004-12-01 00:00:00',
 '2005-01-01 00:00:00': '2005-01-01 00:00:00',
 '2005-02-01 00:00:00': '2005-02-01 00:00:00',
 '2005-03-01 00:00:00': '2005-03-01 00:00:00',
 '2005-04-01 00:00:00': '2005-04-01 00:00:00',
 '2005-05-01 00:00:00': '2005-05-01 00:00:00',
 '2005-06-01 00:00:00': '2005-06-01 00:00:00',
 '2005-07-01 00:00:00': '2005-07-01 00:00:00',
 '2005-08-01 00:00:00': '2005-08-01 00:00:00',
 '2005-09-01 00:00:00': '2005-09-01 00:00:00',
 '2005-10-01 00:00:00': '2005-10-01 00:00:00',
 '2005-11-01 00:00:00': '2005-11-01 00:00:00',
 '2005-12-01 00:00:00': '2005-12-01 00:00:00',
 '2006-01-01 00:00:00': '2006-01-01 00:00:00',
 '2006-02-01 00:00:00': '2006-02-01 00:00:00',
 '2006-03-01 00:00:00': '2006-03-01 00:00:00',
 '2006-04-01 00:00:00': '2006-04-01 00:00:00',
 '2006-05-01 00:00:00': '2006-05-01 00:00:00',
 '2006-06-01 00:00:00': '2006-06-01 00:00:00',
 '2006-07-01 00:00:00': '2006-07-01 00:00:00',
 '2006-08-01 00:00:00': '2006-08-01 00:00:00',
 '2006-09-01 00:00:00': '2006-09-01 00:00:00',
 '2006-10-01 00:00:00': '2006-10-01 00:00:00',
 '2006-11-01 00:00:00': '2006-11-01 00:00:00',
 '2006-12-01 00:00:00': '2006-12-01 00:00:00',
 '2007-01-01 00:00:00': '2007-01-01 00:00:00',
 '2007-02-01 00:00:00': '2007-02-01 00:00:00',
 '2007-03-01 00:00:00': '2007-03-01 00:00:00',
 '2007-04-01 00:00:00': '2007-04-01 00:00:00',
 '2007-05-01 00:00:00': '2007-05-01 00:00:00',
 '2007-06-01 00:00:00': '2007-06-01 00:00:00',
 '2007-07-01 00:00:00': '2007-07-01 00:00:00',
 '2007-08-01 00:00:00': '2007-08-01 00:00:00',
 '2007-09-01 00:00:00': '2007-09-01 00:00:00',
 '2007-10-01 00:00:00': '2007-10-01 00:00:00',
 '2007-11-01 00:00:00': '2007-11-01 00:00:00',
 '2007-12-01 00:00:00': '2007-12-01 00:00:00',
 '2008-01-01 00:00:00': '2008-01-01 00:00:00',
 '2008-02-01 00:00:00': '2008-02-01 00:00:00',
 '2008-03-01 00:00:00': '2008-03-01 00:00:00',
 '2008-04-01 00:00:00': '2008-04-01 00:00:00',
 '2008-05-01 00:00:00': '2008-05-01 00:00:00',
 '2008-06-01 00:00:00': '2008-06-01 00:00:00',
 '2008-07-01 00:00:00': '2008-07-01 00:00:00',
 '2008-08-01 00:00:00': '2008-08-01 00:00:00',
 '2008-09-01 00:00:00': '2008-09-01 00:00:00',
 '2008-10-01 00:00:00': '2008-10-01 00:00:00',
 '2008-11-01 00:00:00': '2008-11-01 00:00:00',
 '2008-12-01 00:00:00': '2008-12-01 00:00:00',
 '2009-01-01 00:00:00': '2009-01-01 00:00:00',
 '2009-02-01 00:00:00': '2009-02-01 00:00:00',
 '2009-03-01 00:00:00': '2009-03-01 00:00:00',
 '2009-04-01 00:00:00': '2009-04-01 00:00:00',
 '2009-05-01 00:00:00': '2009-05-01 00:00:00',
 '2009-06-01 00:00:00': '2009-06-01 00:00:00',
 '2009-07-01 00:00:00': '2009-07-01 00:00:00',
 '2009-08-01 00:00:00': '2009-08-01 00:00:00',
 '2009-09-01 00:00:00': '2009-09-01 00:00:00',
 '2009-10-01 00:00:00': '2009-10-01 00:00:00',
 '2009-11-01 00:00:00': '2009-11-01 00:00:00',
 '2009-12-01 00:00:00': '2009-12-01 00:00:00',
 '2010-01-01 00:00:00': '2010-01-01 00:00:00',
 '2010-02-01 00:00:00': '2010-02-01 00:00:00',
 '2010-03-01 00:00:00': '2010-03-01 00:00:00',
 '2010-04-01 00:00:00': '2010-04-01 00:00:00',
 '2010-05-01 00:00:00': '2010-05-01 00:00:00',
 '2010-06-01 00:00:00': '2010-06-01 00:00:00',
 '2010-07-01 00:00:00': '2010-07-01 00:00:00',
 '2010-08-01 00:00:00': '2010-08-01 00:00:00',
 '2010-09-01 00:00:00': '2010-09-01 00:00:00',
 '2010-10-01 00:00:00': '2010-10-01 00:00:00',
 '2010-11-01 00:00:00': '2010-11-01 00:00:00',
 '2010-12-01 00:00:00': '2010-12-01 00:00:00',
 '2011-01-01 00:00:00': '2011-01-01 00:00:00',
 '2011-02-01 00:00:00': '2011-02-01 00:00:00',
 '2011-03-01 00:00:00': '2011-03-01 00:00:00',
 '2011-04-01 00:00:00': '2011-04-01 00:00:00',
 '2011-05-01 00:00:00': '2011-05-01 00:00:00',
 '2011-06-01 00:00:00': '2011-06-01 00:00:00',
 '2011-07-01 00:00:00': '2011-07-01 00:00:00',
 '2011-08-01 00:00:00': '2011-08-01 00:00:00',
 '2011-09-01 00:00:00': '2011-09-01 00:00:00',
 '2011-10-01 00:00:00': '2011-10-01 00:00:00',
 '2011-11-01 00:00:00': '2011-11-01 00:00:00',
 '2011-12-01 00:00:00': '2011-12-01 00:00:00',
 '2012-01-01 00:00:00': '2012-01-01 00:00:00',
 '2012-02-01 00:00:00': '2012-02-01 00:00:00',
 '2012-03-01 00:00:00': '2012-03-01 00:00:00',
 '2012-04-01 00:00:00': '2012-04-01 00:00:00',
 '2012-05-01 00:00:00': '2012-05-01 00:00:00',
 '2012-06-01 00:00:00': '2012-06-01 00:00:00',
 '2012-07-01 00:00:00': '2012-07-01 00:00:00',
 '2012-08-01 00:00:00': '2012-08-01 00:00:00',
 '2012-09-01 00:00:00': '2012-09-01 00:00:00',
 '2012-10-01 00:00:00': '2012-10-01 00:00:00',
 '2012-11-01 00:00:00': '2012-11-01 00:00:00',
 '2012-12-01 00:00:00': '2012-12-01 00:00:00',
 '2013-01-01 00:00:00': '2013-01-01 00:00:00',
 '2013-02-01 00:00:00': '2013-02-01 00:00:00',
 '2013-03-01 00:00:00': '2013-03-01 00:00:00',
 '2013-04-01 00:00:00': '2013-04-01 00:00:00',
 '2013-05-01 00:00:00': '2013-05-01 00:00:00',
 '2013-06-01 00:00:00': '2013-06-01 00:00:00',
 '2013-07-01 00:00:00': '2013-07-01 00:00:00',
 '2013-08-01 00:00:00': '2013-08-01 00:00:00',
 '2013-09-01 00:00:00': '2013-09-01 00:00:00',
 '2013-10-01 00:00:00': '2013-10-01 00:00:00',
 '2013-11-01 00:00:00': '2013-11-01 00:00:00',
 '2013-12-01 00:00:00': '2013-12-01 00:00:00',
 '2014-01-01 00:00:00': '2014-01-01 00:00:00',
 '2014-02-01 00:00:00': '2014-02-01 00:00:00',
 '2014-03-01 00:00:00': '2014-03-01 00:00:00',
 '2014-04-01 00:00:00': '2014-04-01 00:00:00',
 '2014-05-01 00:00:00': '2014-05-01 00:00:00',
 '2014-06-01 00:00:00': '2014-06-01 00:00:00',
 '2014-07-01 00:00:00': '2014-07-01 00:00:00',
 '2014-08-01 00:00:00': '2014-08-01 00:00:00',
 '2014-09-01 00:00:00': '2014-09-01 00:00:00',
 '2014-10-01 00:00:00': '2014-10-01 00:00:00',
 '2014-11-01 00:00:00': '2014-11-01 00:00:00',
 '2014-12-01 00:00:00': '2014-12-01 00:00:00',
 '2015-01-01 00:00:00': '2015-01-01 00:00:00',
 '2015-02-01 00:00:00': '2015-02-01 00:00:00',
 '2015-03-01 00:00:00': '2015-03-01 00:00:00',
 '2015-04-01 00:00:00': '2015-04-01 00:00:00',
 '2015-05-01 00:00:00': '2015-05-01 00:00:00',
 '2015-06-01 00:00:00': '2015-06-01 00:00:00',
 '2015-07-01 00:00:00': '2015-07-01 00:00:00',
 '2015-08-01 00:00:00': '2015-08-01 00:00:00',
 '2015-09-01 00:00:00': '2015-09-01 00:00:00',
 '2015-10-01 00:00:00': '2015-10-01 00:00:00',
 '2015-11-01 00:00:00': '2015-11-01 00:00:00',
 '2015-12-01 00:00:00': '2015-12-01 00:00:00',
 '2016-01-01 00:00:00': '2016-01-01 00:00:00',
 '2016-02-01 00:00:00': '2016-02-01 00:00:00',
 '2016-03-01 00:00:00': '2016-03-01 00:00:00',
 '2016-04-01 00:00:00': '2016-04-01 00:00:00',
 '2016-05-01 00:00:00': '2016-05-01 00:00:00',
 '2016-06-01 00:00:00': '2016-06-01 00:00:00',
 '2016-07-01 00:00:00': '2016-07-01 00:00:00',
 '2016-08-01 00:00:00': '2016-08-01 00:00:00',
 '2016-09-01 00:00:00': '2016-09-01 00:00:00',
 '2016-10-01 00:00:00': '2016-10-01 00:00:00',
 '2016-11-01 00:00:00': '2016-11-01 00:00:00',
 '2016-12-01 00:00:00': '2016-12-01 00:00:00',
 '2017-01-01 00:00:00': '2017-01-01 00:00:00',
 '2017-02-01 00:00:00': '2017-02-01 00:00:00',
 '2017-03-01 00:00:00': '2017-03-01 00:00:00',
 '2017-04-01 00:00:00': '2017-04-01 00:00:00',
 '2017-05-01 00:00:00': '2017-05-01 00:00:00',
 '2017-06-01 00:00:00': '2017-06-01 00:00:00',
 '2017-07-01 00:00:00': '2017-07-01 00:00:00',
 '2017-08-01 00:00:00': '2017-08-01 00:00:00',
 '2017-09-01 00:00:00': '2017-09-01 00:00:00',
 '2017-10-01 00:00:00': '2017-10-01 00:00:00',
 '2017-11-01 00:00:00': '2017-11-01 00:00:00',
 '2017-12-01 00:00:00': '2017-12-01 00:00:00',
 '2018-01-01 00:00:00': '2018-01-01 00:00:00',
 '2018-02-01 00:00:00': '2018-02-01 00:00:00',
 '2018-03-01 00:00:00': '2018-03-01 00:00:00',
 '2018-04-01 00:00:00': '2018-04-01 00:00:00',
 '2018-05-01 00:00:00': '2018-05-01 00:00:00',
 '2018-06-01 00:00:00': '2018-06-01 00:00:00',
 '2018-07-01 00:00:00': '2018-07-01 00:00:00',
 '2018-08-01 00:00:00': '2018-08-01 00:00:00',
 '2018-09-01 00:00:00': '2018-09-01 00:00:00',
 '2018-10-01 00:00:00': '2018-10-01 00:00:00',
 '2018-11-01 00:00:00': '2018-11-01 00:00:00',
 '2018-12-01 00:00:00': '2018-12-01 00:00:00',
 '2019-01-01 00:00:00': '2019-01-01 00:00:00',
 '2019-02-01 00:00:00': '2019-02-01 00:00:00',
 '2019-03-01 00:00:00': '2019-03-01 00:00:00',
 '2019-04-01 00:00:00': '2019-04-01 00:00:00',
 '2019-05-01 00:00:00': '2019-05-01 00:00:00',
 '2019-06-01 00:00:00': '2019-06-01 00:00:00',
 '2019-07-01 00:00:00': '2019-07-01 00:00:00',
 '2019-08-01 00:00:00': '2019-08-01 00:00:00',
 '2019-09-01 00:00:00': '2019-09-01 00:00:00',
 '2019-10-01 00:00:00': '2019-10-01 00:00:00',
 '2019-11-01 00:00:00': '2019-11-01 00:00:00',
 '2019-12-01 00:00:00': '2019-12-01 00:00:00',
 '2020-01-01 00:00:00': '2020-01-01 00:00:00',
 '2020-02-01 00:00:00': '2020-02-01 00:00:00',
 '2020-03-01 00:00:00': '2020-03-01 00:00:00',
 '2020-04-01 00:00:00': '2020-04-01 00:00:00',
 '2020-05-01 00:00:00': '2020-05-01 00:00:00',
 '2020-06-01 00:00:00': '2020-06-01 00:00:00',
 '2020-07-01 00:00:00': '2020-07-01 00:00:00',
 '2020-08-01 00:00:00': '2020-08-01 00:00:00'}

# Plotting

,93591,93563,93553,93552,93551,93550,93544,93543,93536,93535,...,90011,90010,90008,90007,90006,90005,90004,90003,90002,90001
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.263552,0.088208,0.527287,-0.418151,-0.060403,-0.057299,-0.037297,-0.220981,-0.347122,-0.253503
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.258730,0.087636,0.016875,-0.419799,-0.066421,-0.059181,-0.035128,-0.216976,-0.344070,-0.257170
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.261665,0.091588,-0.003384,-0.418144,-0.070782,-0.053939,-0.038085,-0.215165,-0.345131,-0.259056
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.259693,0.093168,-0.019315,-0.417088,-0.076502,-0.046783,-0.038014,-0.209092,-0.344372,-0.267990
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.258148,0.096523,-0.040955,-0.412415,-0.078811,-0.036197,-0.034909,-0.203073,-0.342667,-0.273338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.035513,2.486325,0.509286,-0.796249,-0.263989,1.156582,0.930786,-0.497881,-0.464415,-0.358798
292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.018529,2.306160,0.525367,-0.806810,-0.281539,1.183946,0.885811,-0.493345,-0.448301,-0.308341
293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.025848,2.416421,0.418059,-0.803190,-0.297364,1.221024,0.853097,-0.488400,-0.449207,-0.309190
294,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.024928,2.432761,0.411495,-0.803997,-0.294577,1.207219,0.833434,-0.486511,-0.450500,-0.306886
295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.023224,2.471809,0.408247,-0.804628,-0.291529,1.188608,0.820393,-0.484200,-0.452924,-0.304958